name: 'Auto PR issue label'
description: 'Auto PR issue labe'
author: 'Auto PR issue labe'
inputs:
  github-token:
    description: 'Github token'
    default: ${{ github.token }}
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
